AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

# disable some cops as this is a prototype
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
